name: Release Please

on:
  push:
    branches: 
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release, please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-${{ github.ref_name }}-config.json
