name: Release Please

on:
  push:
    branches: 
      - main
      - develop

jobs:
  clean_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: sed no beta
        if: github.ref_name == 'main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          sed -i 's/-beta[^ ]*//g' version.txt .release-please-manifest.json
          git add .
          git commit -m "chore: remove beta tags"

  release:
    runs-on: ubuntu-latest
    needs: clean_versions
    steps:
      - name: Release, please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-${{ github.ref_name }}-config.json
